name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install python dependencies
        run: pip install -r ./src/main/resources/requirements.txt
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Coveralls
        run: mvn coveralls:report -DrepoToken=${{ secrets.COVERALLS }}
      - name: Generate Documentation
        run: mvn javadoc:javadoc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: /home/runner/work/jRDF2Vec/jRDF2Vec/target/site/apidocs/ # The folder the action should deploy.
